### ISSUE TITLE
Error on "Login as this user" or "Login as this tenant" - data:text/html,chromewebdata 

### ISSUE THREAD

**Issue by sujanmah062** [aspnetboilerplate/module-zero#333] opened 2017-03-29 06:34 UTC
Hi all,
I'm using Abp.1.4.2.0 version. When I click on "Login as this user" or  "Login as this tenant", while URL redirecting an error occurred as shown in screenshot. This error only exist in chrome browser.
![screenshot_8](https://cloud.githubusercontent.com/assets/25734794/24441488/8456de3e-1479-11e7-8029-c7d7fd0e87dc.png)

**Comment by hikalkan** [comment] 2017-03-31 09:04
duplicate of https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1988

**Closed by hikalkan** 2017-03-31 09:04 UTC
